version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment: # environment 속성을 통해 컨테이너 내부의 OS 환경 변수로 들어감
      SPRING_PROFILES_ACTIVE: default
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
