spring:
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    com.team3: info
    root: info
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
    org.apache.kafka: WARN
    org.springframework.data.elasticsearch.client: TRACE
    org.elasticsearch.client: TRACE
