spring:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: false

logging:
  level:
    com.team3: info
    root: info
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
    org.apache.kafka: WARN
    org.springframework.data.elasticsearch.client: TRACE
    org.elasticsearch.client: TRACE
