spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    com.team3: warn
    root: warn

otboo:
  storage:
    type: s3
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      baseUrl: ${AWS_S3_BUCKET_URL}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}
